### ISSUE TITLE
test script fails on macos M2 processor with the following error

### ISSUE THREAD

**Issue by hvgazula** [neuroneural/wirehead#9]
I followed the steps to the T but I shall try this again.

Update: Ah i guess it's because it is trying to connect to arctrdcn018.rs.gsu.edu:27017? I don't have any privileges at GSU.

```
(wirehead) ➜  unit git:(main) brew services start mongodb-community@7.0
==> Successfully started `mongodb-community` (label: homebrew.mxcl.mongodb-community)
(wirehead) ➜  unit git:(main) ./test.sh
Traceback (most recent call last):
  File "/Users/harsha/Documents/wirehead/examples/unit/clean.py", line 25, in <module>
    main()
  File "/Users/harsha/Documents/wirehead/examples/unit/clean.py", line 20, in main
    delete_database(client, config['DBNAME'])
  File "/Users/harsha/Documents/wirehead/examples/unit/clean.py", line 11, in delete_database
    client.drop_database(db_name)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/mongo_client.py", line 2030, in drop_database
    with self._conn_for_writes(session, operation=_Op.DROP_DATABASE) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1339, in _conn_for_writes
    server = self._select_server(writable_server_selector, session, operation)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1322, in _select_server
    server = topology.select_server(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/topology.py", line 368, in select_server
    server = self._select_server(
             ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/topology.py", line 346, in _select_server
    servers = self.select_servers(
              ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/topology.py", line 253, in select_servers
    server_descriptions = self._select_servers_loop(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/topology.py", line 303, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: arctrdcn018.rs.gsu.edu:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66952d1ad4a5f2b6dad8d3a3, topology_type: Unknown, servers: [<ServerDescription ('arctrdcn018.rs.gsu.edu', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('arctrdcn018.rs.gsu.edu:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
Dataset: config loaded from config.yaml
Generator: Initialized
Manager: Initialized
^_Test failed: name 'ConnectionFailure' is not defined
Traceback (most recent call last):
  File "/Users/harsha/Documents/wirehead/examples/unit/manager.py", line 5, in <module>
Traceback (most recent call last):
  File "/Users/harsha/Documents/wirehead/examples/unit/generator.py", line 16, in <module>
    wirehead_runtime.run_manager()
    wirehead_runtime.run_generator()
  File "/Users/harsha/Documents/wirehead/wirehead/manager.py", line 46, in run_manager
  File "/Users/harsha/Documents/wirehead/wirehead/generator.py", line 127, in run_generator
    self.db["status"].insert_one({"swapped": False})
    self.generate_and_insert()
  File "/Users/harsha/Documents/wirehead/wirehead/generator.py", line 114, in generate_and_insert
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/collection.py", line 658, in insert_one
    index = self.get_current_idx()
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/harsha/Documents/wirehead/wirehead/generator.py", line 100, in get_current_idx
    counter_doc = dbc.find_one_and_update(
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/collection.py", line 3449, in find_one_and_update
    self._insert_one(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/collection.py", line 598, in _insert_one
    self.__database.client._retryable_write(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1575, in _retryable_write
    return self.__find_and_modify(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/collection.py", line 3110, in __find_and_modify
    return self._retry_with_session(retryable, func, s, bulk, operation, operation_id)
    return self.__database.client._retryable_write(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1575, in _retryable_write
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1461, in _retry_with_session
    return self._retry_internal(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1507, in _retry_internal
    return self._retry_with_session(retryable, func, s, bulk, operation, operation_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1461, in _retry_with_session
    ).run()
      ^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/mongo_client.py", line 2353, in run
    return self._retry_internal(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1507, in _retry_internal
    return self._read() if self._is_read else self._write()
                                              ^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/mongo_client.py", line 2456, in _write
    ).run()
      ^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/mongo_client.py", line 2353, in run
    self._server = self._get_server()
                   ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/mongo_client.py", line 2439, in _get_server
    return self._read() if self._is_read else self._write()
                                              ^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/mongo_client.py", line 2456, in _write
    return self._client._select_server(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1322, in _select_server
    self._server = self._get_server()
                   ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/mongo_client.py", line 2439, in _get_server
    server = topology.select_server(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/topology.py", line 368, in select_server
    server = self._select_server(
             ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/topology.py", line 346, in _select_server
    servers = self.select_servers(
              ^^^^^^^^^^^^^^^^^^^^
    return self._client._select_server(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/topology.py", line 253, in select_servers
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/mongo_client.py", line 1322, in _select_server
    server_descriptions = self._select_servers_loop(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/topology.py", line 303, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: arctrdcn018.rs.gsu.edu:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66952d39a30aa61a39ff41bd, topology_type: Unknown, servers: [<ServerDescription ('arctrdcn018.rs.gsu.edu', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('arctrdcn018.rs.gsu.edu:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
    server = topology.select_server(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/topology.py", line 368, in select_server
    server = self._select_server(
             ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/topology.py", line 346, in _select_server
    servers = self.select_servers(
              ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/topology.py", line 253, in select_servers
    server_descriptions = self._select_servers_loop(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/wirehead/lib/python3.12/site-packages/pymongo/topology.py", line 303, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: arctrdcn018.rs.gsu.edu:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 66952d39fcc86fbcc876168a, topology_type: Unknown, servers: [<ServerDescription ('arctrdcn018.rs.gsu.edu', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('arctrdcn018.rs.gsu.edu:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
./test.sh: line 13: terminate_child_processes: command not found
```

**Comment by spikedoanz** [comment]
The connection error was caused by an incorrect default hostname in the configuration. The script was attempting to connect to a GSU server (arctrdcn018.rs.gsu.edu:27017) instead of the local MongoDB instance.

I've fixed it to instead point to localhost, and tested again on Mac M2.
